#ifndef ENTITYIDS_H
#define ENTITYIDS_H

typedef enum
{
    ENTITY_EARTH,
    ENTITY_MOON,
    ENTITY_EARTH_BLOOD,
    ENTITY_MOON_BLOOD,
    ENTITY_BTN_START,
    ENTITY_BTN_EXIT,
    ENTITY_BG_MENU,
    ENTITY_BG_GAME_OVER,
    ENTITY_ENEMY,
    ENTITY_SIDE_BAR,
    ENTITY_ARROW_MINI_MAP
} EntityID;
#endif // ENTITYIDS_H
